// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import './gallery.css';


export default class Gallery extends React.Component {
  render() {
    return (
      <div className="gallery-gallery-20">
          <div className="gallery-0">
              <div className="gallery-gallery-2" style={{"backgroundImage": ("url('"+(this.props.img_src)+"')")}} /> 
          </div>
          <div className="gallery-1" /> 
      </div>
    );
  }
};
