// Generated by https://pagedraw.io/pages/15083
import React from "react";
import "./gallery.css";
import "react-image-gallery/styles/css/image-gallery.css";
import ImageGallery from "react-image-gallery";

export default class Gallery extends React.Component {
  render() {
    const images = [
      {
        original: this.props.img_src,
        thumbnail: this.props.img_src
      },
      {
        original: this.props.img_src,
        thumbnail: this.props.img_src
      },
      {
        original: this.props.img_src,
        thumbnail: this.props.img_src
      }
    ];
    return (
      <div className="gallery-gallery-20">
        <div className="gallery-0">
          <div className="gallery-gallery-2">
            <ImageGallery autoPlay={true} items={images} />
          </div>
        </div>
        <div className="gallery-1" />
      </div>
    );
  }
}
