// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import './peaktime.css';


export default class Peaktime extends React.Component {
  render() {
    return (
      <div className="peaktime-peaktime-0" /> 
    );
  }
};
