// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import './placemap.css';


export default class Placemap extends React.Component {
  render() {
    return (
      <div className="placemap-placemap-3">
          <div className="placemap-0">
              <img src="https://ucarecdn.com/5cf68454-390e-4b3c-ba57-794950ef9b29/" className="placemap-image_8" /> 
          </div>
          <div className="placemap-1" /> 
      </div>
    );
  }
};
