// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import Bystyle from './components/bystyle';
import './explore.css';


export default class Explore extends React.Component {
  render() {
    return (
      <div className="explore-explore-0">
          <div className="explore-0">
              <div className="explore-explore_your_style_-1">
                  Explore Your Style
              </div>
          </div>
          <div className="explore-1">
              <div className="explore-1-0" /> 
              <div className="explore-bystyle-7">
                  <Bystyle text={"Mountain"} /> 
              </div>
              <div className="explore-1-2" /> 
              <div className="explore-bystyle-8">
                  <Bystyle text={"Sea"} /> 
              </div>
              <div className="explore-1-4" /> 
              <div className="explore-bystyle-83">
                  <Bystyle text={"Temple"} /> 
              </div>
              <div className="explore-1-6" /> 
              <div className="explore-bystyle-0">
                  <Bystyle text={"Historical"} /> 
              </div>
              <div className="explore-1-8" /> 
          </div>
          <div className="explore-2">
              <div className="explore-2-0" /> 
              <div className="explore-bystyle-81">
                  <Bystyle text={"Waterfall"} /> 
              </div>
              <div className="explore-2-2" /> 
              <div className="explore-bystyle-07">
                  <Bystyle text={"Cave"} /> 
              </div>
              <div className="explore-2-4" /> 
              <div className="explore-bystyle-2">
                  <Bystyle text={"Shopping Mall"} /> 
              </div>
              <div className="explore-2-6" /> 
              <div className="explore-bystyle-79">
                  <Bystyle text={"Zoo"} /> 
              </div>
              <div className="explore-2-8" /> 
          </div>
      </div>
    );
  }
};
