// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import Header from '../utility/header';
import Tripname from '../customize/tripname';
import Selecteddate from './selecteddate';
import Notselectdate from './notselectdate';
import Date from './date';
import Summary from './summary';
import Maparea from './maparea';
import './summarypage.css';


export default class Summarypage extends React.Component {
  render() {
    return (
      <div className="summarypage-summarypage-7">
          <div className="summarypage-0">
              <div className="summarypage-0-0" /> 
              <div className="summarypage-header_instance-0">
                  <Header /> 
              </div>
              <div className="summarypage-0-2" /> 
          </div>
          <div className="summarypage-1">
              <div className="summarypage-tripname_instance-2">
                  <Tripname name={"Summer Trip"} /> 
              </div>
          </div>
          <div className="summarypage-2">
              <div className="summarypage-2-0">
                  <div className="summarypage-2-0-0">
                      <div className="summarypage-rectangle-8">
                          <div className="summarypage-2-0-0-0-0">
                              <div className="summarypage-2-0-0-0-0-0">
                                  <div className="summarypage-2-0-0-0-0-0-0">
                                      <div className="summarypage-dec_-9">
                                          { 'Dec' }
                                      </div>
                                  </div>
                              </div>
                              <div className="summarypage-selected_instance-4">
                                  <Selecteddate text={"Sat 22"} /> 
                              </div>
                              <div className="summarypage-2-0-0-0-0-2">
                                  <div className="summarypage-2-0-0-0-0-2-0">
                                      <div className="summarypage-notselect_instance1">
                                          <Notselectdate text={"Sun 23"} /> 
                                      </div>
                                  </div>
                              </div>
                              <div className="summarypage-2-0-0-0-0-3">
                                  <div className="summarypage-2-0-0-0-0-3-0">
                                      <div className="summarypage-notselectdate_instance-7">
                                          <Notselectdate text={"Mon 24"} /> 
                                      </div>
                                  </div>
                              </div>
                              <div className="summarypage-2-0-0-0-0-4">
                                  <div className="summarypage-2-0-0-0-0-4-0">
                                      <div className="summarypage-notselectdate_instance_2">
                                          <Notselectdate text={"Tue 26"} /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="summarypage-2-0-1">
                      <div className="summarypage-edit-9">
                          <div className="summarypage-2-0-1-0-0">
                              <div className="summarypage-rectangle_3">
                                  <div className="summarypage-2-0-1-0-0-0-0">
                                      <div className="summarypage-edit_-2">Edit</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="summarypage-2-0-2">
                      <div className="summarypage-date_instance-7">
                          <Date text={"Saturday"} text2={"22 December 2018"} /> 
                      </div>
                  </div>
                  <div className="summarypage-2-0-3">
                      <div className="summarypage-summary_instance-9">
                          <Summary time1={"08:00"} time2={"10:00"} placename={"Place A"} img_src={"https://ucarecdn.com/22923d95-90d4-46bf-ab9a-95e2b7818320/"} openTime={"08.00-12.00"} phone={""} fee={""} /> 
                      </div>
                  </div>
                  <div className="summarypage-2-0-4">
                      <div className="summarypage-summary_instance-7">
                          <Summary time1={"11:00"} time2={"13:00"} placename={"Place B"} img_src={"https://ucarecdn.com/910e76ae-f2ba-47b1-a3a9-5e2a02fc6c65/"} openTime={"06.00-15.00"} phone={""} fee={""} /> 
                      </div>
                  </div>
                  <div className="summarypage-2-0-5">
                      <div className="summarypage-summary_instance_2">
                          <Summary time1={"14:00"} time2={"16:00"} placename={"Place C"} img_src={"https://ucarecdn.com/04bf5346-870a-4a89-835c-e18b226de36c/"} openTime={"13.00-18.00"} phone={""} fee={""} /> 
                      </div>
                  </div>
              </div>
              <div className="summarypage-2-1" /> 
              <div className="summarypage-2-2">
                  <div className="summarypage-2-2-0">
                      <div className="summarypage-rightside-4">
                          <div className="summarypage-2-2-0-0-0">
                              <div className="summarypage-4">
                                  4 Days,10 Places,300 Baht In Songkla
                              </div>
                          </div>
                          <div className="summarypage-2-2-0-0-1">
                              <div className="summarypage-map_instance-7">
                                  <Maparea zone={"Songkla"} places={"4 Places"} fee={"300 Baht"} /> 
                              </div>
                              <div className="summarypage-2-2-0-0-1-1" /> 
                          </div>
                          <div className="summarypage-2-2-0-0-2">
                              <div className="summarypage-buttons-3">
                                  <div className="summarypage-2-2-0-0-2-0-0">
                                      <div className="summarypage-sharebutton-9">
                                          <div className="summarypage-2-2-0-0-2-0-0-0-0">
                                              <div className="summarypage-rectangle_2">
                                                  <div className="summarypage-2-2-0-0-2-0-0-0-0-0-0">
                                                      <div className="summarypage-share_-0">Share</div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div className="summarypage-export-7">
                                          <div className="summarypage-2-2-0-0-2-0-0-1-0">
                                              <div className="summarypage-rectangle_9">
                                                  <div className="summarypage-2-2-0-0-2-0-0-1-0-0-0">
                                                      <div className="summarypage-export_pdf_-8">Export PDF</div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div className="summarypage-sendmail-9">
                                          <div className="summarypage-2-2-0-0-2-0-0-2-0">
                                              <div className="summarypage-rectangle_8">
                                                  <div className="summarypage-2-2-0-0-2-0-0-2-0-0-0">
                                                      <div className="summarypage-send_to_email_-7">
                                                          Send to Email
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
