// Generated by https://pagedraw.io/pages/15083
import React from "react";
import "./component_1.css";

export default class Component_1 extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <span className="component_1-component_1">
        <div className="component_1-0">
          <div className="component_1-image_9">
            <div className="component_1-0-0-0">
              <div className="component_1-wat_arun_-1">{this.props.name}</div>
            </div>
          </div>
        </div>
      </span>
    );
  }
}
