// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import './component_1.css';


export default class Component_1 extends React.Component {
  render() {
    return (
      <div className="component_1-component_1">
          <div className="component_1-0">
              <div className="component_1-image_9">
                  <div className="component_1-0-0-0">
                      <div className="component_1-wat_arun_-1">Wat Arun</div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
