// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import Styletag2 from './components/styletag2';
import './suggestcustom.css';


export default class Suggestcustom extends React.Component {
  render() {
    return (
      <div className="pd-onactive-parent pd-onhover-parent suggestcustom">
          { (('default') === "default") ?
              <div className="suggestcustom-default-3">
                  <div className="suggestcustom-0-0-0">
                      <div className="suggestcustom-image_6" style={{"backgroundImage": ("url('"+(this.props.img_main)+"')")}}>
                          <div className="suggestcustom-0-0-0-0-0">
                              <div className="suggestcustom-styletag2">
                                  <Styletag2 text={this.props.style} /> 
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="suggestcustom-0-0-1">
                      <div className="suggestcustom-place-5">
                          { this.props.place }
                      </div>
                      <div className="suggestcustom-0-0-1-1">
                          <div className="suggestcustom-0-0-1-1-0">
                              <div className="suggestcustom-province-8">
                                  { this.props.province }
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="suggestcustom-0-0-2">
                      <div className="suggestcustom-rating-3" style={{"backgroundImage": ("url('"+(this.props.img_src)+"')")}} /> 
                  </div>
              </div>
          : null}
          <div className="pd-onactive suggestcustom-_active-7">
              <div className="suggestcustom-1-0">
                  <div className="suggestcustom-image_6-7" style={{"backgroundImage": ("url('"+(this.props.img_main)+"')")}}>
                      <div className="suggestcustom-1-0-0-0">
                          <div className="suggestcustom-styletag2_">
                              <Styletag2 text={this.props.style} /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="suggestcustom-1-1">
                  <div className="suggestcustom-place-7">
                      { this.props.place }
                  </div>
                  <div className="suggestcustom-1-1-1">
                      <div className="suggestcustom-1-1-1-0">
                          <div className="suggestcustom-province-7">
                              { this.props.province }
                          </div>
                      </div>
                  </div>
              </div>
              <div className="suggestcustom-1-2">
                  <div className="suggestcustom-rating-0" style={{"backgroundImage": ("url('"+(this.props.img_src)+"')")}} /> 
              </div>
          </div>
          <div className="pd-onhover suggestcustom-_hover-8">
              <div className="suggestcustom-2-0">
                  <div className="suggestcustom-border-6">
                      <div className="suggestcustom-2-0-0-0">
                          <div className="suggestcustom-image_6-2" style={{"backgroundImage": ("url('"+(this.props.img_main)+"')")}}>
                              <div className="suggestcustom-2-0-0-0-0-0">
                                  <div className="suggestcustom-styletag2_i">
                                      <Styletag2 text={this.props.style} /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="suggestcustom-2-0-0-1">
                          <div className="suggestcustom-place-9">
                              { this.props.place }
                          </div>
                          <div className="suggestcustom-2-0-0-1-1">
                              <div className="suggestcustom-2-0-0-1-1-0">
                                  <div className="suggestcustom-province-2">
                                      { this.props.province }
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="suggestcustom-2-0-0-2">
                          <div className="suggestcustom-rating-8" style={{"backgroundImage": ("url('"+(this.props.img_src)+"')")}} /> 
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
