// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import './tripname.css';
import EditableLabel from 'react-editable-label';


export default class Tripname extends React.Component {
  render() {
    return (
      <div className="tripname-tripname-8">
          <div className="tripname-0">
              <div className="tripname-tripname-9">
                  <EditableLabel
                      initialValue={ this.props.name }
                      save={value => {console.log(`Saving '${value}'`);}}
                        />
              </div>
          </div>
      </div>
    );
  }
};
