// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import Header from './header';
import Tripname from './tripname';
import Component_1 from './component_1';
import Suggestcustom from './suggestcustom';
import './customize.css';


export default class Customize extends React.Component {
  render() {
    return (
      <div className="customize-customize-7">
          <div className="customize-0">
              <div className="customize-0-0" /> 
              <div className="customize-header_instance_2">
                  <Header /> 
              </div>
              <div className="customize-0-2" /> 
          </div>
          <div className="customize-1">
              <div className="customize-1-0">
                  <div className="customize-1-0-0">
                      <img src="https://ucarecdn.com/9e342169-5e36-4b8d-9fee-a71376228ca1/" className="customize-image_1" /> 
                  </div>
              </div>
              <div className="customize-tripname_instance_2">
                  <Tripname name={"Summer Trip"} /> 
              </div>
          </div>
          <div className="customize-2">
              <div className="customize-rectangle_4" /> 
          </div>
          <div className="customize-3">
              <div className="customize-buddy_basket_-8">
                  Buddy Basket
              </div>
              <div className="customize-visited_places_-9">
                  Visited Places
              </div>
          </div>
          <div className="customize-4">
              <div className="customize-4-0">
                  <div className="customize-4-0-0">
                      <div className="customize-rectangle_5" /> 
                  </div>
                  <div className="customize-4-0-1">
                      <div className="customize-suggested_places_-1">
                          Suggested Places
                      </div>
                  </div>
              </div>
              <div className="customize-4-1">
                  <div className="customize-4-1-0">
                      <div className="customize-rectangle_6">
                          <div className="customize-4-1-0-0-0">
                              <div className="customize-component_1_">
                                  <Component_1 /> 
                              </div>
                              <div className="customize-component_1_">
                                  <Component_1 /> 
                              </div>
                              <div className="customize-component_1_">
                                  <Component_1 /> 
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="customize-5">
              <div className="customize-rectangle_7">
                  <div className="customize-5-0-0">
                      <div className="customize-5-0-0-0">
                          <div className="customize-5-0-0-0-0">
                              <div className="customize-5-0-0-0-0-0">
                                  <div className="customize-suggestcustom_instance-6">
                                      <Suggestcustom place={"Place A"} province={"Songkla"} img_src={"https://ucarecdn.com/4ddffb97-e590-4649-abab-290493e11cf9/"} style={"Temple"} img_main={"https://ucarecdn.com/577034a5-7ea0-4b21-898a-c364e7d818a6/"} /> 
                                  </div>
                              </div>
                          </div>
                          <div className="customize-5-0-0-0-1">
                              <div className="customize-5-0-0-0-1-0">
                                  <div className="customize-suggestcustom_instance_2">
                                      <Suggestcustom place={"Place B"} province={"Songkla"} img_src={"https://ucarecdn.com/ec629618-5d41-4d33-86d5-0cb12ee243ed/"} style={"Zoo"} img_main={"https://ucarecdn.com/646c21d3-59ea-4f2e-b8d7-2ef590d80bb6/"} /> 
                                  </div>
                              </div>
                          </div>
                          <div className="customize-5-0-0-0-2">
                              <div className="customize-5-0-0-0-2-0">
                                  <div className="customize-suggestcustom_instance_3">
                                      <Suggestcustom place={"Place C"} province={"Songkla"} img_src={"https://ucarecdn.com/9823c134-1e88-4c2b-84b9-0e5f084adc23/"} style={"Mountain"} img_main={"https://ucarecdn.com/fcf691fa-7146-4aab-a066-18cdeeb772eb/"} /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="customize-5-0-0-1" /> 
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
