// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import './date.css';


export default class Date extends React.Component {
  render() {
    return (
      <div className="date-date-9">
          <div className="date-0">
              <div className="date-saturday_-5">{ this.props.text }</div>
              <div className="date-0-1">
                  <div className="date-0-1-0">
                      <div className="date-2">{ this.props.text2 }</div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
