// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import './header.css';
import Sticky from 'react-stickynode'

export default class Header extends React.Component {
  render() {
    return (
    <Sticky>
      <div className="header-header-1">
          <div className="header-0" /> 
          <div className="header-1">
              <div className="header-1-0" /> 
              <div className="header-1-1">
                  <div className="header-1-1-0" /> 
                  <div className="header-1-1-1">
                      <div className="header-tripnotize_-2">Tripnotize</div>
                  </div>
                  <div className="header-1-1-2" /> 
              </div>
              <div className="header-1-2" /> 
              <div className="header-utils-7">
                  <div className="header-1-3-0" /> 
                  <div className="header-1-3-1">
                      <div className="header-1-3-1-0">
                          <div className="header-1-3-1-0-0">
                              <div className="header-my_trips_-6">My Trips</div>
                          </div>
                      </div>
                      <div className="header-line-3" /> 
                      <div className="header-1-3-1-2">
                          <div className="header-1-3-1-2-0">
                              <div className="header-sign_up_-5">Sign Up</div>
                          </div>
                      </div>
                      <div className="header-line-4" /> 
                      <div className="header-1-3-1-4">
                          <div className="header-1-3-1-4-0">
                              <div className="header-sign_in_-9">Sign In</div>
                          </div>
                      </div>
                  </div>
                  <div className="header-1-3-2" /> 
              </div>
              <div className="header-1-4" /> 
              <div className="header-1-5">
                  <div className="header-1-5-0" /> 
                  <div className="header-1-5-1">
                      <img src="https://ucarecdn.com/45490e93-6b20-48a6-a0fd-e118f76760dc/" className="header-image_5" /> 
                  </div>
                  <div className="header-1-5-2" /> 
              </div>
              <div className="header-1-6" /> 
          </div>
          <div className="header-2" /> 
      </div>
    </Sticky>
    );
  }
};
