// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import Header from './header';
import Mainimage from './mainimage';
import Startpanel from './startpanel';
import Description from './description';
import Recommendplace from './recommendplace';
import Explore from './explore';
import './homepage.css';


export default class Homepage extends React.Component {
  render() {
    return (
      <div className="homepage-homepage-1">
          <div className="homepage-0">
              <div className="homepage-0-0" /> 
              <div className="homepage-header-8"><Header /> </div>
              <div className="homepage-0-2" /> 
          </div>
          <div className="homepage-1">
              <div className="homepage-1-0" /> 
              <div className="homepage-image_instance-5">
                  <Mainimage /> 
              </div>
              <div className="homepage-1-2" /> 
          </div>
          <div className="homepage-2">
              <div className="homepage-2-0" /> 
              <div className="homepage-startpanel_instance-3">
                  <Startpanel /> 
              </div>
              <div className="homepage-2-2" /> 
          </div>
          <div className="homepage-3">
              <div className="homepage-3-0" /> 
              <div className="homepage-description_instance-1">
                  <Description /> 
              </div>
              <div className="homepage-3-2" /> 
          </div>
          <div className="homepage-4">
              <div className="homepage-4-0" /> 
              <div className="homepage-recommend_instance-8">
                  <Recommendplace /> 
              </div>
              <div className="homepage-4-2" /> 
          </div>
          <div className="homepage-5">
              <div className="homepage-5-0" /> 
              <div className="homepage-explore_instance-9">
                  <Explore /> 
              </div>
              <div className="homepage-5-2" /> 
          </div>
      </div>
    );
  }
};
