// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import './mainimage.css';


export default class Mainimage extends React.Component {
  render() {
    return (
      <div className="mainimage-mainimage-4">
          <div className="mainimage-0">
              <div className="mainimage-0-0" /> 
              <div className="mainimage-image-9">
                  <div className="mainimage-0-1-0">
                      <div className="mainimage-0-1-0-0" /> 
                      <div className="mainimage-travel_in_thailand_-8">
                          <div>Travel</div>
                          <div>In</div>
                          <div>Thailand</div>
                      </div>
                      <div className="mainimage-0-1-0-2" /> 
                  </div>
              </div>
              <div className="mainimage-0-2" /> 
          </div>
      </div>
    );
  }
};
