// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import './notselectdate.css';


export default class Notselectdate extends React.Component {
  render() {
    return (
      <div className="notselectdate-notselectdate-0">
          <div className="notselectdate-0">
              <div className="notselectdate-sat2">
                  { this.props.text }
              </div>
          </div>
      </div>
    );
  }
};
