// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import Recommend from './recommend';
import './recommendplace.css';


export default class Recommendplace extends React.Component {
  render() {
    return (
      <div className="recommendplace-recommendplace-5">
          <div className="recommendplace-0">
              <div className="recommendplace-recommended_places_-1">
                  Recommended Places
              </div>
          </div>
          <div className="recommendplace-1">
              <div className="recommendplace-1-0" /> 
              <div className="recommendplace-recommend-7">
                  <Recommend place={"Place A"} province={"Songkla"} img_src={"https://ucarecdn.com/b0f2be76-d906-45f4-9518-f64f185d9402/"} style={"Temple"} img_rate={"https://ucarecdn.com/6ca3a5f2-ab9d-43a5-b068-01f18b19acae/"} /> 
              </div>
              <div className="recommendplace-1-2" /> 
              <div className="recommendplace-recommend-5">
                  <Recommend place={"Place2"} province={"Songkla"} img_src={"https://ucarecdn.com/b012d21c-da45-404f-aafa-10400c166086/"} style={"Sea"} img_rate={"https://ucarecdn.com/6498b600-5cb4-4810-8f8f-6017d5373f46/"} /> 
              </div>
              <div className="recommendplace-1-4" /> 
              <div className="recommendplace-recommend-6">
                  <Recommend place={"Place3"} province={"rrrr"} img_src={"https://ucarecdn.com/f6a5e2ad-0164-4b74-bf99-3e0f5fcd815b/"} style={"Temple"} img_rate={"https://ucarecdn.com/3ad54c17-67d5-4e9e-81c5-69e1a392f2d3/"} /> 
              </div>
              <div className="recommendplace-1-6" /> 
              <div className="recommendplace-recommend-9">
                  <Recommend place={"Place4"} province={"bkk"} img_src={"https://ucarecdn.com/2e0e2b5e-3058-44a0-b553-55b6a19ff592/"} style={"Waterfall"} img_rate={"https://ucarecdn.com/f76c70d3-2287-478f-a6e4-8009f0298f25/"} /> 
              </div>
              <div className="recommendplace-1-8" /> 
          </div>
      </div>
    );
  }
};
