// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import './startpanel.css';
import Customize from './customize'
import DestinationDrop from './destination';
import NationDrop from './nationality';
import StylePop from './styleselect';
import DatePop from './datepick';
import PropTypes from "prop-types";
import { Button } from 'semantic-ui-react';

export default class Startpanel extends React.Component {
  constructor(props) {
    super(props);
    }
    static contextTypes = {
        router: PropTypes.object
      }

    changeRoute = () => {
        this.context.router.history.push('/trip-custom');
    }

  render() {
    return (
      <div className="startpanel-startpanel-6">
          <div className="startpanel-0">
              <div className="startpanel-0-0" /> 
              <div className="startpanel-startpannel-3">
                  <div className="startpanel-0-1-0">
                      <div className="startpanel-0-1-0-0" /> 
                      <div className="startpanel-0-1-0-1">
                          <div className="startpanel-0-1-0-1-0" /> 
                          <div className="startpanel-0-1-0-1-1">
                              <div className="startpanel-destinationbutton-5">
                                  <div className="startpanel-0-1-0-1-1-0-0">
                                      <img src="https://ucarecdn.com/dcc965e3-b3be-4456-902b-e48a1b41f7f8/" className="startpanel-location-0" /> 
                                      <div className="startpanel-0-1-0-1-1-0-0-1" >
                                        <div className = "startpanel-destination_-8">
                                            <DestinationDrop />
                                        </div>
                                      </div>
                                      <div className="startpanel-0-1-0-1-1-0-0-2">
                                          <div className="startpanel-0-1-0-1-1-0-0-2-0">
                                              {/* <img src="https://ucarecdn.com/9201e6b7-db8e-40a6-ad57-aff951b52626/" className="startpanel-drop-1" />  */}
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="startpanel-0-1-0-1-2" /> 
                      </div>
                      <div className="startpanel-0-1-0-2" /> 
                      <div className="startpanel-0-1-0-3">
                          <div className="startpanel-0-1-0-3-0" /> 
                          <div className="startpanel-0-1-0-3-1">
                              <div className="startpanel-line1" /> 
                          </div>
                          <div className="startpanel-0-1-0-3-2" /> 
                      </div>
                      <div className="startpanel-0-1-0-4" /> 
                      <div className="startpanel-0-1-0-5">
                          <div className="startpanel-0-1-0-5-0" /> 
                          <div className="startpanel-0-1-0-5-1">
                              <div className="startpanel-startend-1">
                                  <div className="startpanel-0-1-0-5-1-0-0">
                                      <img src="https://ucarecdn.com/74ce9628-8729-4324-bc57-0eada5e9f21b/" className="startpanel-calender-3" /> 
                                      <div className="startpanel-0-1-0-5-1-0-0-1">
                                          <div className="startpanel-0-1-0-5-1-0-0-1-0">
                                              <DatePop/>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="startpanel-0-1-0-5-2" /> 
                      </div>
                      <div className="startpanel-0-1-0-6" /> 
                      <div className="startpanel-0-1-0-7">
                          <div className="startpanel-0-1-0-7-0" /> 
                          <div className="startpanel-0-1-0-7-1">
                              <div className="startpanel-line2" /> 
                          </div>
                          <div className="startpanel-0-1-0-7-2" /> 
                      </div>
                      <div className="startpanel-0-1-0-8" /> 
                      <div className="startpanel-0-1-0-9">
                          <div className="startpanel-0-1-0-9-0" /> 
                          <div className="startpanel-0-1-0-9-1">
                              <div className="startpanel-nationalbutton-0">
                                  <div className="startpanel-0-1-0-9-1-0-0">
                                      <img src="https://ucarecdn.com/32c03395-56b6-48d6-a88d-b893b9f3c7ee/" className="startpanel-people-1" /> 
                                      <div className="startpanel-0-1-0-9-1-0-0-1">
                                          <div className="startpanel-0-1-0-9-1-0-0-1-0">
                                              <div className="startpanel-nationality_-0">
                                                  <NationDrop />
                                              </div>
                                          </div>
                                      </div>
                                      <div className="startpanel-0-1-0-9-1-0-0-2">
                                          <div className="startpanel-0-1-0-9-1-0-0-2-0">
                                              {/* <img src="https://ucarecdn.com/9201e6b7-db8e-40a6-ad57-aff951b52626/" className="startpanel-drop-10" />  */}
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="startpanel-0-1-0-9-2" /> 
                      </div>
                      <div className="startpanel-0-1-0-10" /> 
                      <div className="startpanel-0-1-0-11">
                          <div className="startpanel-0-1-0-11-0" /> 
                          <div className="startpanel-0-1-0-11-1">
                              <div className="startpanel-line3" /> 
                          </div>
                          <div className="startpanel-0-1-0-11-2" /> 
                      </div>
                      <div className="startpanel-0-1-0-12" /> 
                      <div className="startpanel-0-1-0-13">
                          <div className="startpanel-0-1-0-13-0" /> 
                          <div className="startpanel-0-1-0-13-1">
                              <div className="startpanel-style-1">
                                  <div className="startpanel-0-1-0-13-1-0-0">
                                      <img src="https://ucarecdn.com/00ab33f9-5c02-4cd8-bab0-b23b02af3688/" className="startpanel-list-2" /> 
                                      <div className="startpanel-0-1-0-13-1-0-0-1">
                                          <div className="startpanel-0-1-0-13-1-0-0-1-0">
                                              <StylePop className="startpanel-style_-2"></StylePop>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="startpanel-0-1-0-13-2" /> 
                      </div>
                      <div className="startpanel-0-1-0-14" /> 
                      <div className="startpanel-0-1-0-15">
                          <div className="startpanel-0-1-0-15-0" /> 
                          <div className="startpanel-0-1-0-15-1">
                              <div className="startpanel-startbutton-0" onClick={this.changeRoute} >
                                  <div className="startpanel-0-1-0-15-1-0-0">
                                      <div className="startpanel-start_plan_-2" >
                                      Start Plan</div>
                                  </div>
                              </div>
                          </div>
                          <div className="startpanel-0-1-0-15-2" /> 
                      </div>
                  </div>
              </div>
              <div className="startpanel-0-2" /> 
          </div>
      </div>
    );
  }
};
