// Generated by https://pagedraw.io/pages/15083
import React from 'react';
import './description.css';


export default class Description extends React.Component {
  render() {
    return (
      <div className="description-description-2">
          <div className="description-0">
              <div className="description-0-0" /> 
              <div className="description-0-1">
                  <div className="description-0-1-0">
                      <div className="description-element1">
                          <div className="description-0-1-0-0-0">
                              <div className="description-image_1" /> 
                          </div>
                          <div className="description-0-1-0-0-1">
                              <div className="description-desc_4">
                                  Auto Generate
                                  <div className="description-desc-down">
                                    Generate a complete travel plan at a desired destination with a few simple steps
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="description-0-2" /> 
              <div className="description-0-3">
                  <div className="description-0-3-0">
                      <div className="description-element2">
                          <div className="description-0-3-0-0-0">
                              <div className="description-image_3" /> 
                          </div>
                          <div className="description-0-3-0-0-1">
                              <div className="description-desc_1">
                                  Customization
                                  <div className="description-desc-down">
                                    Traveller can customize places and time in a travel plan to make desired travel plan
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="description-0-4" /> 
              <div className="description-0-5">
                  <div className="description-0-5-0">
                      <div className="description-element3">
                          <div className="description-0-5-0-0-0">
                              <div className="description-image_2" /> 
                          </div>
                          <div className="description-0-5-0-0-1">
                              <div className="description-desc_2">
                                  Export To PDF
                                  <div className="description-desc-down">
                                    The completed plan can be exported to PDF which provide more convenience on viewing offline in any devices
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="description-0-6" /> 
              <div className="description-0-7">
                  <div className="description-0-7-0">
                      <div className="description-element4">
                          <div className="description-0-7-0-0-0">
                              <div className="description-image_4" /> 
                          </div>
                          <div className="description-0-7-0-0-1">
                              <div className="description-desc_3">
                                  AI Implemented
                                  <div className="description-desc-down">
                                    The AI engines provide the places that best match personal styles and find the best route for travelling
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="description-0-8" /> 
          </div>
      </div>
    );
  }
};
