// Generated by https://pagedraw.io/pages/15083
import React from "react";
import "./tripSlot.css";

export default class TripSlot extends React.Component {
  render() {
    return (
      <div className="summary-summary-0">
        <div className="summary-1">
          <div className="summary-1-1">
            <div className="summary-1-1-0">
              <img src={this.props.img_src} className="summary-image_7" />
            </div>
          </div>
          <div className="summary-1-">
            <div className="summary-1-2-0">
              <div className="summary-place_a_-0">Tripname : MySummerTrip</div>
            </div>
          </div>
          <div className="summary-1-2">
            <div className="summary-1-2-1">
              <div className="summary-open_time_-7">{"Duration :"}</div>
            </div>
            <div className="summary-1-2-2">
              <div className="summary-tel-4">{"Province :"}</div>
            </div>
            <div className="summary-1-2-3">
              <div className="summary-fee-2">{"Date Created :"}</div>
            </div>
          </div>
          <div className="summary-1-2-">
            <div className="summary-1-2-1">
              <div className="summary-8">3</div>
            </div>
            <div className="summary-1-2-2">
              <div className="summary-086">4</div>
            </div>
            <div className="summary-1-2-3">
              <div className="summary-086">5</div>
            </div>
          </div>
          <div className="summary-extra"></div>
          <div className="summary-1-3">
            <div className="summarypage-export-7">
              <div className="summarypage-2-2-0-0-2-0-0-1-0">
                <div className="summarypage-rectangle_9">
                  <div className="summarypage-2-2-0-0-2-0-0-1-0-0-0">
                    <div className="summarypage-export_pdf_-8">
                      View
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="summary-1-3">
            <div className="summarypage-export-7">
              <div className="summarypage-2-2-0-0-2-0-0-1-0">
                <div className="summarypage-rectangle_9">
                  <div className="summarypage-2-2-0-0-2-0-0-1-0-0-0">
                    <div className="summarypage-export_pdf_-8">
                      Export PDF
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
